language: c

compiler: gcc

before_install:
        - sudo apt-get update
        - sudo apt-get install valgrind
        - pip install --user cpp-coveralls

script:
        - make test

after_success:
        - coveralls --gcov-options '\-lp'

