.TH dodo 1 dodo\-VERSION

.SH NAME
dodo - a scriptable in place file ditor

.SH SYNOPSIS
.B dodo filename


.SH DESCRIPTION
dodo is a scriptable in place file editor

dodo takes exactly 1 argument, the file to work on

dodo takes it's program input from stdin

.SH Author
Dodo was made by Chris Hall <followingthepath AT gmail d0t com>

.SH Bugs
Report them.
