.TH dodo 1 dodo\-VERSION

.SH NAME
dodo - a dumb todo list manager

.SH SYNOPSIS
.B dodo
.RB [ -a
.RI task
.RI description ]
.RB [ -d
.RI task
.RI description ]
.RB [ path | - ]

.SH DESCRIPTION
dodo is a dumb todo list manager

.SH Author
Dodo was made by Chris Hall <followingthepath AT gmail d0t com>

.SH Bugs
Report them.
